language: python

python:
  - "3.4"

branches:
  only:
    - master
    - develop

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install blender
  - pip install pylint
  - pip install pep8

install:
  - wget http://mirror.cs.umn.edu/blender.org/release/Blender2.77/blender-2.77-linux-glibc211-x86_64.tar.bz2
  - tar jxf blender-2.77-linux-glibc211-x86_64.tar.bz2
  - cp -r uv_magic_uv blender-2.77-linux-glibc211-x86_64/2.77/scripts/addons

before_script:
  - bash tests/check_code_style.sh uv_magic_uv

script: blender-2.77-linux-glibc211-x86_64/blender --factory-startup --background -noaudio --python tests/run_tests.py
